export const icons = [
    {value: "home", title: "Casa 1", icon: "home"},
    {value: "storefront", title: "Tienda", icon: "storefront"},
    {value: "restaurant", title: "Restaurante 1", icon: "restaurant"},
    {value: "location_city", title: "Edificio", icon: "location_city"},
    {value: "restaurant_menu", title: "Restaurante 2", icon: "restaurant_menu"},
    {value: "house", title: "Casa 2", icon: "house"},
    {value: "corporate_fare", title: "Corporativo", icon: "corporate_fare"},
    {value: "cottage", title: "Cabaña", icon: "cottage"},
    {value: "domain", title: "Corporativo 2", icon: "domain"},
    {value: "holiday_village", title: "Fraccionamiento", icon: "holiday_village"},
    {value: "account_balance", title: "Banco 1", icon: "account_balance"},
    {value: "food_bank", title: "Banco 2", icon: "food_bank"},
    {value: "gite", title: "Gite", icon: "gite"},
    {value: "villa", title: "Escuela", icon: "villa"},
    {value: "home_filled", title: "Casa 3", icon: "home_filled"},
    {value: "cabin", title: "Cabaña", icon: "cabin"},
    {value: "local_hospital", title: "Hospital local", icon: "local_hospital"},
    {value: "local_laundry_service", title: "Servicio de lavandería local", icon: "local_laundry_service"},
    {value: "bedroom_child", title: "Dormitorio infantil", icon: "bedroom_child"},
    {value: "spa", title: "Spa", icon: "spa"},
    {value: "hot_tub", title: "Jacuzzi", icon: "hot_tub"},
    {value: "fitness_center", title: "Centro de fitness", icon: "fitness_center"},
    {value: "sports_mma", title: "Deportes de MMA", icon: "sports_mma"},
    {value: "sports_martial_arts", title: "Deportes de artes marciales", icon: "sports_martial_arts"},
    {value: "store", title: "Tienda", icon: "store"},
    {value: "local_grocery_store", title: "Tienda de comestibles local", icon: "local_grocery_store"},
    {value: "warehouse", title: "Almacén", icon: "warehouse"},
    {value: "liquor", title: "Licorería", icon: "liquor"},
    {value: "store_mall_directory", title: "Directorio de centros comerciales", icon: "store_mall_directory"},
    {value: "local_fire_department", title: "Departamento de bomberos local", icon: "local_fire_department"},
    {value: "local_library", title: "Biblioteca local", icon: "local_library"},
    {value: "local_cafe", title: "Cafetería local", icon: "local_cafe"},
    {value: "local_police", title: "Policía local", icon: "local_police"},
    {value: "local_parking", title: "Aparcamiento local", icon: "local_parking"},
    {value: "local_bar", title: "Bar local", icon: "local_bar"},
    {value: "local_airport", title: "Aeropuerto local", icon: "local_airport"},
    {value: "museum", title: "Museo", icon: "museum"},
    {value: "local_pharmacy", title: "Farmacia local", icon: "local_pharmacy"},
    {value: "festival", title: "Festival", icon: "festival"},
    {value: "local_convenience_store", title: "Tienda de conveniencia local", icon: "local_convenience_store"},
    {value: "local_movies", title: "Cine local", icon: "local_movies"},
    {value: "stadium", title: "Estadio", icon: "stadium"}
];